### ISSUE TITLE
Is there a way to force a deck out of the deck?

### ISSUE THREAD

**Issue by OakandRocks** [SimonTheChain/deck_of_cards#5]
I coded some blackjack stuff for fun but I can't seem to hit two A's, not sure if i'm just unlucky or if something's buggy.

I need to force a specific card.value (1) onto an object/list

**Comment by SimonTheChain** [comment]
You could try to empty the deck (if needed) with give_random_card(), give_first_card() or give_last_card(), then insert the cards you want into the deck:

card = deck_of_cards.Card((2, 11))  # 2=suit, 11=rank
deck_obj.take_card(card)

But the easiest way to verify what you want is to print out the deck:
deck_obj.print_deck()
